### ISSUE TITLE
Remove Chinese characters 

### ISSUE THREAD

**Issue by onanboy** [jacquesh/foo_openlyrics#108]
A lot of the lyrics contain Chinese characters especially for the song title or band name.  Is there a simple way to auto-remove those characters with a right-click?

**Comment by mrbentarikau** [comment]
or some kind of regex replace

**Comment by daoxi** [comment]
> A lot of the lyrics contain Chinese characters especially for the song title or band name. Is there a simple way to auto-remove those characters with a right-click?

Most lyrics contain Chinese characters because the two default online lyrics sources (QQ Music and NetEase Cloud Music) are both Chinese platforms.
It might be a little hard to automate if it's included as part of the scrolling lyrics (but easy to remove manually as they're always at the top), we can also consider a feature that removes the [ID tags in LRC lyrics](https://en.wikipedia.org/wiki/LRC_(file_format)#Simple_format) such as:
```
[ar:Lyrics artist]
[al:Album where the song is from]
[ti:Lyrics (song) title]
```

**Comment by onanboy** [comment]
You're correct that these characters can be manually removed or even better, just ignored.  
Don't sweat it everyone.  I withdraw the request, if that is possible.
