### ISSUE TITLE
What kind of embedded lyrics are supported?

### ISSUE THREAD

**Issue by Zapeth** [jacquesh/foo_openlyrics#125]
If I understood https://github.com/jacquesh/foo_openlyrics/issues/84 correctly, ID3v2.3 tags for unsynced lyrics should be supported (via `UNSYNCED LYRICS` setting in foobar2000) while synced lyrics are not?

I have an mp3 with a `USLT` tag, however no lyrics are displayed in the OpenLyrics Panel or with the "Show Lyrics" option (I set the `UNSYNCED LYRICS` option as first and the lyrics sources are just set to "Local files").

If I play the file in WMP the lyrics show up as expected, the tag list in foobar2000 look like this:
![Untitled](https://user-images.githubusercontent.com/11491561/169578140-15228f27-97b6-47e3-9dc6-cb8b7123de16.jpg)

Also, what other kinds of metadata formats for unsynched lyrics tag are (un)supported? https://wiki.hydrogenaudio.org/index.php?title=Tag_Mapping#Miscellaneous

I'm specifically interested in Vorbis Comment formats, but setting the `LYRICS` comment-tag didn't seem to have any effect either (no lyrics are displayed, but it shows up in the tag list).

**Comment by jacquesh** [comment]
If you want to load lyrics from tags, you must have the "ID3 tags" source enabled. Admittedly the naming isn't *technically* correct in all cases but its close enough I think.

If you have the tag source enabled and the tag that fb2k shows is in the list of tags to search, then openlyrics will find it.

**Comment by Zapeth** [comment]
Thanks, that was indeed the issue. I didn't even think to look at the list of disabled sources, because I expected it to be enabled by default (and thought it was included with the "Local files" source).

Also yes, the naming is a bit unfortunate. Maybe something like "Embedded tags" or "Metadata tags" would be more appropriate, but I guess most users using this feature will also have heard of ID3 tags.

**Comment by jacquesh** [comment]
Oh thats actually a good point, I don't know of any specific reason why we shouldn't have tags enabled by default. I'll add it in.

I like the name "Metadata tags" since its technically more correct (not every file uses ID3 tag specifically, ogg uses vorbis comments), is probably more widely recognisable ("ID3 tags" is technical jargon that people may not know) and matches with fb2k's own naming (if you open track properties, the tab that shows tags is titled "Metadata".

Good ideas all round, thanks!
