### ISSUE TITLE
"Collapse multiple instances of the same line" is no longer working

### ISSUE THREAD

**Issue by Sevenuno** [jacquesh/foo_openlyrics#130]
I normally don't check the .lrc files. I just realize that this function is no longer working since ver. 1.1

**Comment by jacquesh** [comment]
Ah, yikes. This was removed in 1a963fd49 because it made the code simpler and I figured nobody cares about the disk space savings. I totally forgot that this was a user-visible setting.

I'm leaning towards just removing the option and keeping the current (never-collapse) behaviour in the interest of simplicity. If anybody desperately wants to keep the collapse behaviour then now is your chance to make that known (but no promises).

**Comment by Sevenuno** [comment]
It really not because of disk space savings.  Though not very often, I reckon that some of us may wish to edit the lyrics manually to correct typos in one or two lines.  If same lines are grouped together, I just need to correct one line and there is no need to look for similar lines manually.  This can be done via an external editor but it's nice if we can do it with the app.  Anyway, it's not something critical and it's up to you.
