### ISSUE TITLE
Change default Lyrics fields

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#150]
Currently it is -
For Unsynced - UNSYNCEDLYRICS
For Synced - LYRICS

Change it to -
For Unsynced - LYRICS
For Synced -  SYNCEDLYRICS

https://wiki.hydrogenaud.io/index.php?title=Tag_Mapping#:~:text=Script-,Synced%20Lyrics,LYRICS,-Additional%20Information

**Comment by jacquesh** [comment]
Has this changed recently? See #84 for a discussion where I specifically changed everything to use "UNSYNCED LYRICS" by default because that's what fb2k would internally translate to store in the USLT ID3 frame.

Can you confirm that fb2k stores "LYRICS" tags in USLT but not "UNSYNCED LYRICS" on the latest version?

**Comment by Rexadev** [comment]
for Vorbis as I have set
it stores in SYNCEDLYRICS for Synced Lyrics 
it stores in LYRICS for UnSynced Lyrics

**Comment by jacquesh** [comment]
I checked. fb2k does indeed (in v1.6.7) store the "UNSYNCED LYRICS" tag in the USLT frame for mp3 files. In formats such as ogg and flac which use Vorbis comments there is no special handling or structure for tags, they're just key-value pairs of utf8 data (https://www.xiph.org/vorbis/doc/v-comment.html) so no particular values are better or worse than any others there.

In short: there is good reason to keep the current defaults (as openlyrics's settings UI actually explains) and there is no reason to change them for Vorbis files.
