### ISSUE TITLE
Feature suggestion: disable lyric searching for specific folders of songs

### ISSUE THREAD

**Issue by u12bdragon** [jacquesh/foo_openlyrics#153]
I have a lofi folder/foobar playlist, and every time a new song comes on, openlyrics searches for lyrics. Since it is lofi, there are no lyrics, so this is pointless. I am proposing a "blacklist" where we can add directories, and for those files/folders, it will never perform a lyric search.

**Comment by jacquesh** [comment]
openlyrics will already stop searching for lyrics for these tracks after a while (off the top of my head I think the limit is currently 3 failed searches and a week since the first search).

Forcing this behaviour is covered by the "Mark as instrumental" auto-edit which is currently available only for individual tracks in the lyrics context menu.

Forcing this behaviour for many tracks at once is covered by making "Mark as instrumental" (among other actions) an option in the playlist menu, available in the next release. At that point you just need to select all your lofi music and mark it as instrumental once, and openlyrics will not search for lyrics for those tracks until you manually search for lyrics for that track (and technically there is also a way to remove all of these "instrumental tags" for all tracks by deleting a particular config file).

**Comment by u12bdragon** [comment]
👍

**Comment by u12bdragon** [comment]
Amazing, man. Love this plugin. Great work!
