### ISSUE TITLE
Only search using First Artist when separator is preset or Album Artist

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#165]
Search doesn't work in songs with multiple artists having metadata in format Artist1; Artist2 or Artist1, Artist2

**Comment by jacquesh** [comment]
We already search for only the first instance of a tag, so if you want to include multiple artists but only search for one, put them in separate "artist" tags. I don't want to do text processing on the tag values to split by comma or semicolon or whatever.

**Comment by Rexadev** [comment]
![Screenshot 2022-09-11 000337](https://user-images.githubusercontent.com/62152714/189600503-e5debb4c-a341-4e8d-b244-02c4e12d4465.png)

**Comment by jacquesh** [comment]
Please don't sneak bug reports into the comments on a feature suggestion. Create a new issue.

I assume you mean the fact that when you open the manual search it populates artist with only "Samra" and not the other two. I expect that metadata panel is showing the value of all the tags, separated by semi-colons in which case this is working as intended.

**Comment by Rexadev** [comment]
> Please don't sneak bug reports into the comments on a feature suggestion. Create a new issue.

OK but I thought it is related so...

> I expect that metadata panel is showing the value of all the tags, separated by semi-colons in which case this is working as intended.

I asked you to only search bt first artist but you said that is a bad idea and now I am saying open_lyrics automatically only using first artist

**Comment by jacquesh** [comment]
> OK but I thought it is related so...

True, but its easier to manage if bugs and feature suggestions are in separate issues (and if there's only 1 bug/feature in each issue). :)

> I asked you to only search bt first artist but you said that is a bad idea and now I am saying open_lyrics automatically only using first artist

There are 2 possible scenarios: 1) A track has 2+ artists, each in a separate copy of the "ARTIST" tag or 2) The track has 2+ artists all strung together in the same tag.

I'm saying we already search only the first artist in case 1 and I don't want to try to specifically solve case 2. If you can demonstrate that what you have is an instance of case 1 and it's not behaving as expected then we have a bug, otherwise I don't think there's anything to do here. If you'd like to claim that its not behaving as expected then please can you provide specific examples and logs (as per the bug report template) and we can re-open this as a bug.

**Comment by Rexadev** [comment]
> I'm saying we already search only the first artist in case 1 and I don't want to try to specifically solve case 2. If you can demonstrate that what you have is an instance of case 1 and it's not behaving as expected then we have a bug, otherwise I don't think there's anything to do here. If you'd like to claim that its not behaving as expected then please can you provide specific examples and logs (as per the bug report template) and we can re-open this as a bug.

I am using 2) and I get only first artist

**Comment by Rexadev** [comment]
I have a good reason - SOurces like Genius and AZLyrics almost always works when only using Album/Main Artist

@jacquesh
