### ISSUE TITLE
Fetch lyrics also when OpenLyrics panel is hidden

### ISSUE THREAD

**Issue by TT-ReBORN** [jacquesh/foo_openlyrics#177]
Hi Jacques,

can you make an option to enable lyrics fetching also when the OpenLyrics panel is hidden in the DUI/CUI layout?
This works for Lyrics Show 3 panel but not for OpenLyrics, it will start searching only when the panel is visible.
I have my own script to parse and display the lyrics, so I don't need the whole panel in my theme. 
I'm certain other devs would also appreciate this option.

When do you plan to make OpenLyrics with streaming ( radio ) compatible?

I really want to switch to OpenLyrics and bury the old Lyrics Show 3 component once and for all, but these two important
missing features are preventing me to do that.

Thanks and keep up the good work!

-TT

**Comment by jacquesh** [comment]
Radios are #49. I don't any specific plans or timelines for that at the moment.

When you say "enable lyrics fetching also when the OpenLyrics panel is hidden". What do you mean by "hidden"? If you mean "there is no OpenLyrics panel present in layout" then I'm tempted to say "no" because 1) that would require a significant rearrangement of how lyric searching gets triggered and 2) supporting lyric fetching other than to show it on the (openlyrics) panel inside fb2k is not a goal for the project.

You could always add an openlyrics panel to your layout and make it small & blend into the background (match the background colour of the rest of the application, make lyrics the same colour so you don't see anything scrolling, etc).

In what way is the openlyrics panel insufficient (enough to justify using your own separate display)?

**Comment by TT-ReBORN** [comment]
I'm the author of [Georgia-ReBORN](https://github.com/TT-ReBORN/Georgia-ReBORN) and I have a special layout.
That means I only have one big SMP. Lyrics are handled by the theme itself.

It looks like this, and the vertical splitter is hidden, I'm only using the component for lyrics fetching:

![Hidden_Panel](https://user-images.githubusercontent.com/79368795/186952934-cabe0bc8-b0f1-44b8-8fc1-fa16c82c7375.jpg)

If I replace Lyrics Show 3 panel with your OpenLyrics panel and hide it, it does not start fetching lyrics, only when it's not hidden.

I think some other themes are also using this trick.

-TT

**Comment by jacquesh** [comment]
Do you know what the significance of marking panels as "Hidden" is? How is it different to just not having the panels in the tree in the first place?

I'd have to investigate how ColumnsUI actually calls down to the panel in that situation.

**Comment by TT-ReBORN** [comment]
Sorry but I have no idea. 
@reupen ( dev of Columns UI ) knows the answer. @reupen can you please help us out? Thank you.

I can tell you only this, OpenLyrics works when the panel is either open in a new window, i.e via command `fb.RunMainMenuCommand('View/OpenLyrics Panel');` or it's visible ( not hidden ). 
It starts searching for lyrics and when it's found ( saved on HDD ), it will be immediately displayed.

With a hidden Lyrics Show 3 Panel panel, it fetches without problems with the multi-source component.

I thought this is no big deal and you could add this as a setting in the Preferences > OpenLyrics options.

-TT

**Comment by reupen** [comment]
Hidden simply makes the panel zero width or height.

**Comment by jacquesh** [comment]
Note to the reader: there is some good discussion about this (now marked as off-topic) in #286. In particular it seems like the only requests that would happen if we allow this, that wouldn't while we don't, is requests skipped while fb2k is minimized. This is also likely to be a tiny minority of requests and therefore unlikely to matter.

It would be worth at least attempting this to see how complicated it would be. I anticipate significant complexity or rework because of the current threading model and how saving is handled. I could easily be wrong though!

It also occurs to me that if we do this then it would probably be reasonable to see if there's an easy way to expose a notification that other plugins can listen for to learn about newly-retrieved lyrics.

**Comment by jacquesh** [comment]
> predefined OpenLyrics settings which I will provide the user with the foo_openlyrics.dll.cfg file.

Oh interesting. Do you do this by just creating the config in fb2k and then saving the config file, or do you have a parser for the format? I semi-regularly want to manually decode config files and I know what the format is for most of the file (it's mostly a list of GUIDs with a length and a value) but there's a bunch of data at the beginning that I don't know the format of, and if you know of somewhere that this is documented, that'd be helpful :)
