### ISSUE TITLE
Show "past lyrics" in darker text

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#178]
![image](https://user-images.githubusercontent.com/62152714/187071267-638c17b3-a500-4822-b63f-c70b7d2c861b.png)

**Comment by regorxxx** [comment]
Changes could be not limited only to past lyrics, but also a transparency to the firsts and last lines at bottom/top. 
That way transition and scrolling of text seems more natural, with text at center getting the attention at first sight. 

Note the current horizontal scrolling effect has that problem, focus goes naturally from left to right for occidental readers, and unless you make the text lighter (or in the example at top, darker, i.e. with transparency), focus goes to the first line naturally instead of the center.

![image](https://user-images.githubusercontent.com/83307074/196010502-b253887a-b800-40b0-b182-93fff72a5893.png)

**Comment by sigma2017** [comment]
Hello, one dumb question, what I have to do to highlight the current verse? 
I put red as custom highlight color but doesn't show, all the text is white.
Thanks.

**Comment by jacquesh** [comment]
@sigma2017 It will only highlight the current verse if the available lyrics are synchronised (IE if they have timestamps, which you'd see at the beginning of each line if you open the editor).

**Comment by Rexadev** [comment]
```
// Get the current track's metadata
metadb_handle_ptr track = playback_control::get()->get_now_playing();
if (!track.is_valid()) {
  return;
}

// Get the track's lyric ID
GUID lyric_id;
if (!track->get_guid(GUID_LYRICS3, &lyric_id)) {
  return;
}

// Get the lyric viewer
lyric_viewer *viewer = static_cast<lyric_viewer *>(uie::window::find_by_guid(guid_lyric_viewer));
if (!viewer) {
  return;
}

// Get the lyric viewer's window handle
HWND hwnd = viewer->get_wnd();

// Set the color of the played lyrics to gray
CHARFORMAT2 cf;
ZeroMemory(&cf, sizeof(cf));
cf.cbSize = sizeof(cf);
cf.dwMask = CFM_COLOR;
cf.crTextColor = RGB(128, 128, 128);
for (int i = 0; i < viewer->get_line_count(hwnd); i++) {
  int len = viewer->get_line_length(hwnd, i);
  viewer->set_char_format(hwnd, i, 0, len, cf);
}

```

**Comment by jacquesh** [comment]
@Rexadev where are all these code snippets coming from? Did you write them? In what context? They definitely appear to use a bunch of code that doesn't exist in openlyrics.
