### ISSUE TITLE
Cache search results in autosearch.

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#195]
> How you think the new feature/improvement would be helpful, or what problem you think it would solve

When manually searching for lyrics after foo_openlyrics has automatically searched for it, it will make it faster to search and choose which lyrics user wants

> If there are similar features already, why the new feature/enhancement would be an improvement over those

No

**Comment by jacquesh** [comment]
I think not. It seems like the benefit wouldn't be worthwhile because:
1. My general assumption is that manual search is comparatively rare (autosearch usually finds something reasonable and you edit from there, if it doesn't you manual search once, save the result and then you're done for that track, possibly with some editing later) and so it wouldn't really be adding all that much value.
2. If you're manual searching then presumably it has already done an autosearch and you didn't like the result, so making it immediately provide that result wouldn't help much anyway.
3. If you have auto-save enabled (which you generally should) then it will find the saved lyrics almost immediately.

It's true that this would reduce load on the lyric sources, but as long as point 1 is true for the majority of users, the difference is pretty small (and probably not worth the complexity).

**Comment by Rexadev** [comment]
User if wants can re-search

**Comment by Rexadev** [comment]
@jacquesh Please reconsider this feature
