### ISSUE TITLE
File name format doesn't create folders

### ISSUE THREAD

**Issue by regorxxx** [jacquesh/foo_openlyrics#201]
File name format doesn't accept folder levels, although the displayed example works fine (image 1). Backslashes are converted to '-'
![image](https://user-images.githubusercontent.com/83307074/196009716-c155e752-72dc-4ebc-a1f2-3648f699f0cc.png)

So the subfolder must always be put at the directory TF.
![image](https://user-images.githubusercontent.com/83307074/196009708-a2fcb0b2-8e52-424c-83a7-e25476a8053e.png)

#### Steps to reproduce
1. Put on file name format: lyrics\[%Track% - ][%title%]
2. Save a lyric file
3. Will be saved into the custom directory format (for ex. C:\TEST\) but not at  C:\TEST\lyrics\..... Filename will be 'lyrics - [%Track% - ][%title%]'

#### Expected behavior
File name should also create subfolders.

#### Versions
* foobar2000 version: 1.6.12
* OpenLyrics version: 1.3

**Comment by jacquesh** [comment]
I'm fairly certain this was by design (and is why the two fields are specifically named "file name" and "directory"). Although off the top of my head right now I can't think of a good user-facing reason to actually enforce it.

If you're using "Custom directory" for the directory then I don't think there's any reason why you'd specifically need this but in other cases it provides more flexibility (maybe you want it next to the track but in a `lyrics` subdirectory, as in your example, although you could already achieve that with the formatted custom directory so ¯\\_(ツ)_/¯).

**Comment by regorxxx** [comment]
In either case that's a bug (display or functionality). Lyrics 3 allows to do that btw.

Now about why to allow that... note only the custom directory option allows to create folder
![image](https://user-images.githubusercontent.com/83307074/196050465-c21b13d5-d0c3-42cb-8aec-ec9a228c91c1.png)

But what about saving lyrics using the other 2 options? You can not create subfolders, since the track TF doesn't allow it :)
![image](https://user-images.githubusercontent.com/83307074/196050475-cc966cf1-5024-4ebf-9d3d-a13c7a7a1d5d.png)
![image](https://user-images.githubusercontent.com/83307074/196050479-885e3c16-d965-4fae-b950-92ac325ef6cf.png)

So that was the original reason to support it in Lyrics 3. To create nested levels in the other 2 options.
