### ISSUE TITLE
Full Screen Lyrics.

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#203]
>- How you think the new feature/improvement would be helpful, or what problem you think it would solve

Sometimes I want to read the lyrics better, show other person, do karaoke etc I want to make it bigger without touching my configuration.

Double click on empty space of foo_openlyrics plugin should trigger this. And have option to open in Full Screen or Windowed by default. Also remember window size.
Use `F11` to switch between FullScreen and Windowed mode.

**Comment by jacquesh** [comment]
This sounds like a job for a separate UI plugin ("Temporarily fullscreen any panel" which, off the top of my head, sounds entirely feasible) than for openlyrics specifically, and since you do always have the option of editing your layout to achieve this (meaning it would only be a quality-of-life improvement for a niche use-case), I don't think so.

Another alternative to modifying the layout would be to have your primary layout saved to file, along with a layout will lyrics fullscreen, and then just load that when you want to have them on display (for karaoke or whatever). Obviously this is more effort than if openlyrics could do it for you, but its an alternative.

**Comment by Rexadev** [comment]
Double click to full screen is a common behavior in foobar2000 components

**Comment by jacquesh** [comment]
@Rexadev As you implied in the other ticket, this is effectively an extension of #41. The changes you want are much less likely to be implemented if you try to motivate them with an unsubstantiated claim on an issue that's been closed for months. If you think fullscreening is an important part of the feature, then I suggest mentioning it in that issue. :)

**Comment by Rexadev** [comment]
My use case is karaeoke-ing
@jacquesh
