### ISSUE TITLE
Parallel search multiple songs

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#217]
> - How you think the new feature/improvement would be helpful, or what problem you think it would solve

User selects 100 songs and uses RightClick>SearchForLyrics.
It takes less time to select 4 groups on 25 songs to search and tag.

**Comment by jacquesh** [comment]
No. Bulk search is slow by design (to avoid spamming web sources) and is intended to be a mostly-background fire-and-forget process.

I've added #223 to enforce this idea and prevent parallel bulk-search (while still providing reasonable UX in allowing users to request searches for different tracks/albums/selections).
