### ISSUE TITLE
In auto-search option to select longest lyric

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#219]
> - How you think the new feature/improvement would be helpful, or what problem you think it would solve

In MusixMatch generally the longest is the best lyrics

foo_openlyrics shows the first lyric it find for it to work search has to complete and the lyrics woould then be shown or changed.

https://github.com/jacquesh/foo_openlyrics/issues/195

Things to consider
if user changes song before search is complete.
User closes foobar2000 before search is complete.

Related https://github.com/jacquesh/foo_openlyrics/issues/345

**Comment by Rexadev** [comment]
Related https://github.com/jacquesh/foo_openlyrics/issues/149

**Comment by Rexadev** [comment]
Things to consider
if user changes song before search is complete.
User closes foobar2000 before search is complete.

**Comment by jacquesh** [comment]
I don't think this would because it would mean moving away from the current ordering by metadata match which is important for selecting lyrics for the correct track, since some sources will happily return lyrics for tracks that are not at all what you searched for and our only mechanism for avoiding those is comparing the given lyric metadata to our track metadata.
