### ISSUE TITLE
Context Menu Capitalization rewording rearranging suggestions

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#222]
Capitalization and rewording
```
Show lyrics > Show Lyrics
Search for lyrics > Search Lyrics
Search for lyrics (manually) > Search Lyrics Manually
Edit lyrics > Edit Lyrics
Mark as instrumental > Mark Instrumental
```

Rearrange to 

```
Search for lyrics
Search for lyrics (manually)
Mark as instrumental
Edit lyrics
Show lyrics
```

**Comment by jacquesh** [comment]
Why? Please provide some justification for changes you suggest.

**Comment by Rexadev** [comment]
Capitalization - Looks cleaner
rewording - Looks shorter

Rearrange 

Now
```
Show lyrics
Search for lyrics
Search for lyrics (manually)
Edit lyrics
Mark as instrumental
```

to
```
Search for lyrics                      - Used for bulk auto tagging. and is most used
Search for lyrics (manually)    - Similar options should be together
Mark as instrumental             - Bulk mark songs as Instrumental
Edit lyrics                                 - Most people will use Panel>RightClick>Edit
Show lyrics                              - At the end before people rarely just read lyrics
```



@jacquesh

**Comment by Rexadev** [comment]
@jacquesh reconsider this

**Comment by jacquesh** [comment]
@Rexadev Listen. I appreciate your interest in openlyrics and its improvement, but I need you to please:
1. Not @ me. There is almost never a good reason to @ me on issues in the repo. I already get notifications for everything that happens on this repo, you do not need to @ me. I have seen your messages and either I have replied or I have chosen not to reply. @-ing me serves no purpose other than to generate annoyance. Please stop doing this.
2. Do not add "[reopen this]", or anything to that effect, to issue titles. Ever. That information belongs in the comments, not in the issue title.
3. If you want me to reconsider a change that I've previously said I'm not going to do, then you need to provide additional justification. Why do you want this change? What benefit would it provide? Are there other examples of the same thing in other software? etcetc. None of this is specific to openlyrics, or even to open-source software in general. If you want somebody to do something (for free, to your benefit), you need to provide some justification for why they might want to do that.
<br/>In this case, you've given some examples and the justification that it "Looks cleaner" or "Looks shorter". I can understand why "looks cleaner" would be beneficial, but its also pretty subjective. "Shorter" isn't subjective, but its also not clear to me that shorter is better in this scenario. You have not provided any further justification for either.
<br/>For example, I specifically opted for sentence case over title case because I believe that to be preferable in most cases as per some technical writing guidelines I saw a while back (I don't recall where). You are asking me to change that. I took 10 seconds to search for some resources on when to use which casing strategy (something you apparently did not do, or if you did you neglected to include the results in your comment) and the first result I got was [this article from Grammarly](https://www.grammarly.com/blog/title-case-sentence-case/) claiming that it's partly a matter of preference and title case is usually used in more formal settings (which is not what openlyrics is). Another thing you could have taken 10 seconds to do is see what the result of fb2k does and try to use a consistency argument. For example the fb2k "File" menu contains the options "New playlist", "Load playlist" and "Save playlist". This also supports my choice of sentence case. Of course there are other examples that use Title Case (such as the tree entries in Preferences: "Keyboard Shortcuts", "Context Menu" etc), but at the very least it means there is precedent for using either (and the Sentence case examples are possibly more applicable because they're menu items).

Constructing justified responses like this takes time. I need to protect my time but I'm also trying not to block you from this repo because as I say, I appreciate your interest. However you have been warned about this sort of thing in the past. If you continue to waste my time with low-effort and often minimally-justified requests for me to do work that is of questionable value, I will be forced to block you.
