### ISSUE TITLE
Relative lyric path for saving/search (foobar portable)

### ISSUE THREAD

**Issue by snowbie** [jacquesh/foo_openlyrics#23]
Not sure if this is a plugin issue or a foobar issue (I use the portable version), and being able to search ".../profile/lyrics" would be convenient since I often send a few friends my foobar folder. On their end, the absolute path is different so the lyrics aren't found.

I'm not sure if it's already supported or if my syntax is messed up/something's not configured correctly, since the portable version of foobar already supports relative pathing (I couldn't get the pathing to work with LyricShowPanel3 either though)

**Comment by jacquesh** [comment]
What would you like the path to be relative to? The foobar executable? I have not tested any of this but:

* In theory the "Save to custom directory" should work with paths relative to the working directory you started foobar from (which might not be the executable directory if you started it from a shortcut, for example).
* I would expect that the current "Save to configuration directory" option would work for portable installations, since it is using foobar's own definition of "profile directory" that I would expect to be correctly set for portable installations.

**Comment by snowbie** [comment]
> 
> 
> What would you like the path to be relative to? The foobar executable? I have not tested any of this but:
> 
>     * In theory the "Save to custom directory" should work with paths relative to the working directory you started foobar from (which might not be the executable directory if you started it from a shortcut, for example).
> 
>

I think the best option for the path would be directly to the primary directory (containing foobar2000.exe), and pathing from there allows anyone to use a custom path they've expanded from there.
Regarding the "configuration directory" pathing, I haven't experimented with that yet tbqh. I was under the assumption it did put it in _a_ folder somewhere the portable installation (foobar2000/profile/configurations), but mine has 36 cfg files what I assumed are for backing up the settings people choose for their components. That's why I didn't consider it, because I have all of my various song-related data stored in their own specific folders under foobar/profile. One being lyrics, another being the massive folder of album art (foobar2000/profile/art), etc

Maybe I misunderstood the "configuration" directory, so I'll save some lyrics using that setting and see where they end up being sent to.

**Comment by jacquesh** [comment]
@snowbie did you try out the "configuration directory" setting? If so did it work for your use-case? I'm closing this since I haven't heard back from you and at face value it seems to me that should work. Feel free to reply/re-open if it does not.
