### ISSUE TITLE
v2 calls all metadata types ID3

### ISSUE THREAD

**Issue by Rexadev** [jacquesh/foo_openlyrics#231]
### v2 Beta 14
![image](https://user-images.githubusercontent.com/62152714/204984237-f0ae844e-3b9c-4fa1-bee4-cf64de29d69f.png)

### v1.6.14
![image](https://user-images.githubusercontent.com/62152714/204983144-781908e5-f3f1-4997-a071-6100c117d862.png)

#### Steps to reproduce
1.
2.
3.

#### Versions

* foobar2000 version:
* OpenLyrics version:

**Comment by jacquesh** [comment]
Again this is a change that was made to openlyrics at some point. Please confirm you're using the same version of openlyrics in both cases, and which version that is.

Closing for now (since it seems most likely that this is a version mismatch issue). Can reopen later if that turns out not to be the case.

**Comment by Rexadev** [comment]
@jacquesh I am using openlyrics v1.6.14 in both
