### ISSUE TITLE
Forward slash '/' in %title% creates a folder

### ISSUE THREAD

**Issue by b0nk** [jacquesh/foo_openlyrics#244]
Forward slash '/' in %title% creates a folder and a file in the lyrics directory

#### Steps to reproduce
1. Play a track with a title containing a '/' example "foo/bar"
2. Save lyrics using the default scheme "[%artist% - ][%title%]"
3. Notice the lyrics directory now has a new folder with "ArtistName - foo" and inside it a file called "bar.txt"

#### Expected behavior
The slash in the filename should be replaced by another character (example "ArtistName - foo_bar.txt")

#### Versions
* foobar2000 version: 1.6.16
* OpenLyrics version: 1.5

#### Additional information
I am using foobar on linux under wine

**Comment by regorxxx** [comment]
I don't consider this a bug at all, and applying a "fix" to a behavior intended by design would be counterproductive.
You should replace yourself those chars via TF. https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Title_Formatting_Reference#.24replace.28str.2Csearch.2Creplace.29

That's how it works on every other plugin or instance where TF is used, so don't really understand what you were expecting here... and all other lyrics plugins work the same.

**Comment by jacquesh** [comment]
Thanks for the help @regorxxx, I'm content to point people to that as a workaround (I just wasn't sure if titleformat provided a nice way to do it).

**Comment by b0nk** [comment]
Nevermind, I can't use spaces or apostrophes
This one works: `[%artist% - ]$replace(%title%,/,_)`

**Comment by regorxxx** [comment]
My recommendation:
$ascii($replace(%title%,\,,/,))
