### ISSUE TITLE
The pluguin fails to get lyrics from MusicXmatch due to different album title

### ISSUE THREAD

**Issue by Ruke805** [jacquesh/foo_openlyrics#266]
#### Steps to reproduce
1. Bulk search for lyrics

#### Expected behavior

Should get the lyrics based on the artist's name and song's title, as in a manual search

#### Versions

* foobar2000 version: 1.6.16
* OpenLyrics version:  1.6

#### Additional information

Some logs:

```
INFO-OpenLyrics: Spawning bulk search window...
INFO-OpenLyrics: Initializing bulk search window...
INFO-OpenLyrics: Searching for lyrics for artist='Nightwish', album='Wishmaster', title='Wishmaster'...
INFO-OpenLyrics: Querying for track ID from https://apic-desktop.musixmatch.com/ws/1.1/track.search?user_language=en&app_id=web-desktop-app-v1.0&subtitle_format=lrc&q_artist=Nightwish&q_album=Wishmaster&q_track=Wishmaster&usertoken=
INFO-OpenLyrics: Rejected Musixmatch search result Nightwish/Wishmaster/Wishmaster due to tag mismatch: Nightwish/Tales From the Elvenpath - Best Of/Wishmaster
INFO-OpenLyrics: Rejected Musixmatch search result Nightwish/Wishmaster/Wishmaster due to tag mismatch: Nightwish/Over The Hills And Far Away/Wishmaster - Live at Hartwall Arena
INFO-OpenLyrics: Rejected Musixmatch search result Nightwish/Wishmaster/Wishmaster due to tag mismatch: Nightwish/End of an Era (Live)/Wishmaster (Live)
INFO-OpenLyrics: Rejected Musixmatch search result Nightwish/Wishmaster/Wishmaster due to tag mismatch: Nightwish/From Wishes To Eternity (Live)/Wishmaster (Live)
INFO-OpenLyrics: Failed to retrieve lyrics from source: Musixmatch
INFO-OpenLyrics: Failed to retrieve lyrics from source: Metadata tags
INFO-OpenLyrics: Parsing lyrics text...
INFO-OpenLyrics: Parsing LRC lyric text...
INFO-OpenLyrics: Lyric loading complete
INFO-OpenLyrics: Received empty lyric update, ignoring...
```

The tags are correct
Artist: Nightwish
Title: Wishmaster
Album: Wishmaster

This song has synced lyrics, which can be found on Spotify: https://open.spotify.com/album/4u5Ik7NMYl3EITJngbMS4V
According to the MusicXMatch site. this album exists in their database: https://www.musixmatch.com/album/Nightwish/Wishmaster

Another thing, if the album title is different, like a "Limited Edition", "Deluxe" etc...it doesn't work as well.

**Comment by jacquesh** [comment]
This is working as expected. If the source provides album info and you have album info set locally in metadata, it will reject mismatches (in the same way that it does for artist & title).

Technically we could ignore album data when checking matches but the fact that this has not been requested until now suggests that it's a rare issue. Unless this is a very common issue (e.g if half of all searches are failing due to album mismatch), the expectation is to just use manual search. The autosearch is never going to be perfect in all cases and is not expected to be.

If a lot of people want it, I can look into adding an option to disregard album mismatches but at this point I'm unconvinced that it'd be worthwhile.

**Comment by jacquesh** [comment]
Actually I see it has been requested before in #164. I'll close this one and that can remain as the primary tracker for this issue.

**Comment by AsuToki360** [comment]
Man, I honestly wished the feature of disabling album requirement is included, no clue why they're not planned of adding that feature, I have a personal compilation of mine and the Musixmatch search fails due to mismatch album name, forcing to search it manually, and it's really annoying.
