### ISSUE TITLE
Openlyrics has been blocked by Smart app control

### ISSUE THREAD

**Issue by Sentsuki** [jacquesh/foo_openlyrics#293]
It shows "Some features of foobar2000 may not work because we can't confirm who published foo_openlyrics.dll that the app tried to load."

Refer to https://support.microsoft.com/en-us/topic/smart-app-control-has-blocked-part-of-this-app-0729fff1-48bf-4b25-aa97-632fe55ccca2, maybe need a signature.

#### Versions

* foobar2000 version:1.6.16
* OpenLyrics version:1.6

**Comment by jacquesh** [comment]
To my understanding signing things (the only way to properly prevent this that I'm aware of) costs a significant amount of money. So that's not happening anytime soon. foobar itself isn't signed, it's just been around for long enough and is used widely enough that MS knows it isn't malware.

I assume there is some way to tell Windows that openlyrics isn't malware (try checking the properties of the extension dll and see if there's an "Unblock" button or similar?), so I'd recommend doing that as a workaround.
