### ISSUE TITLE
Skip lyrics with only a single line at 00:00

### ISSUE THREAD

**Issue by Velocidensity** [jacquesh/foo_openlyrics#301]
It's quite common to see user submissioons on QQ Music and NetEase, which only have a single line, less commonly two, with song writer credits, but no actual lyrics.

**Comment by jacquesh** [comment]
In general: No. I'm not making guesses about the "correctness" of lyrics on the basis of incredibly fuzzy signals about the shape of the returned text (a similar thing was requested in #242). What if there is actually only one line of lyrics? What if the track is instrumental and that's what the lyrics data says (which is conceivably desirable)? How do we determine if the single line contains only "credits"? etc.

In theory I could add an autoedit for "Remove single-line lyrics" or something but that wouldn't help you because that only runs after lyrics have been retrieved and has no input on the lyric selection process. My recommendation would be to move those two sources further down in the search-source list.

What would your desired behaviour be in the case that a lyric with one line containing mostly-credits is found?

**Comment by Velocidensity** [comment]
I'd like to discard them entirely. You raise good points. and I agree that user-configurable discard filters you mention in #242 would be a good replacement.

**Comment by aaronliu0130** [comment]
> incredibly fuzzy signals about the shape of the returned text 

Well, in my suggestion the shape wasn't fuzzy. It was a line of text that could only ever appear in instrumentals

**Comment by jacquesh** [comment]
I believe this will be covered by #242 and source-specific solutions like #423
