### ISSUE TITLE
Default SKIP filter does not work for multivalue tags

### ISSUE THREAD

**Issue by regorxxx** [jacquesh/foo_openlyrics#307]
#### Steps to reproduce
1. Use a track with multiple genres like: Instrumental\\Rock
2. Use default filter (with https://github.com/jacquesh/foo_openlyrics/issues/306 fixed)
`$stricmp(%genre%,instrumental)$stricmp(%genre%,classical)
`
![image](https://github.com/jacquesh/foo_openlyrics/assets/83307074/a8cf32c1-5dfa-40c7-b5ca-cc3d514052c6)

#### Expected behavior
Track should be skipped.

#### Versions
* OpenLyrics version: 1.7

#### Additional information
Filter should not use $stricmp but $strstr
`$if($or($strstr($lower(%genre%),instrumental),$strstr($lower(%genre%),classical)),skip,)`

![image](https://github.com/jacquesh/foo_openlyrics/assets/83307074/d47f6949-d042-40a4-b174-2eb7d8281b8f)

**Comment by jacquesh** [comment]
Good idea, thanks for suggesting it. I'll add this in the bugfix release for #306.

...Can you tell I don't use titleformat strings all that often? >_<

**Comment by jacquesh** [comment]
I opted to just concatenate single `$if()` statements, rather than use `$or()` because that gets clumsy really quickly when you add more options (since fb2k's `$or()` doesn't support more than two arguments, or at least so says the documentation). This way you can just keep tacking new `$if()`s to the end.

This is also why the scheme is "empty string to search" rather than "this particular string".
