### ISSUE TITLE
First line of lyrics not being displayed if within brackets

### ISSUE THREAD

**Issue by Shinisuryu** [jacquesh/foo_openlyrics#32]
I've noticed that if the first line of lyrics are within brackets, such as [Verse 1: *singer*], it's not displayed. Any lines after that are fine, brackets or not. On 0.7.

**Comment by jacquesh** [comment]
All lyrics are parsed as being in LRC format and LRC supports files starting with "tags" (specifying metadata like track title or artist).

I believe the parser does not currently check that lines of the matching format are actually valid tags, which is why it's eating those first lines. Should be a fairly simple fix, it should just check that tag-like lines contain valid tags before it removes them.
