### ISSUE TITLE
netease: wrong results for artist "3"

### ISSUE THREAD

**Issue by veksha** [jacquesh/foo_openlyrics#34]
![image](https://user-images.githubusercontent.com/275333/126917537-a56f8e64-3853-435f-a7c1-cd940f8a9065.png)

**Comment by jacquesh** [comment]
Have you seen the same search parameters give more sensible results from NetEase elsewhere? I suspect this is just NetEase giving back strange search results (rather than openlyrics passing bad search params).

The NetEase search code has not changed (with the exception of a minor change to the url encoding but I get the same results from them either way). Just trying some random queries locally (without OpenLyrics just making the equivalent requests manually), NetEase seems to return strange results for music that isn't wildly popular.

**Comment by veksha** [comment]
lyric sources tend to return strange results. so our job is to implement some clever (or simple) filtering :)
something like:   `if bigger contains smaller, ....`

**Comment by jacquesh** [comment]
Yeah I did think about doing some basic filtering for the manual search but then the whole point of it is that OpenLyrics gets out of your way and just shows you exactly what the sources provide. Adding filtering to that seems like it goes against the purpose of the manual search feature. The point of listing all the results is that the user can then decide for themselves which results make sense or not, rather than OpenLyrics trying to do that automatically (probably incorrectly excluding some results in some cases) and then giving the user the choice anyway.

The normal (non manual) search does filter these out by checking that results are within some arbitrary levenshtein distance of the search parameters, so this should not affect the automated search.

**Comment by veksha** [comment]
I didn't know that automated search already has this filter. so this is not so scary as i thought. :) if garbage results will be too much in the future, you can always easily implement an option to enable this filter in manual search as well.
