### ISSUE TITLE
Add a column to manual search for "LRC"/timestamped status

### ISSUE THREAD

**Issue by jacquesh** [jacquesh/foo_openlyrics#40]
So that people can see from the tab (without having to click on each item) which lyrics are timestamped or not.

Reported @ https://www.reddit.com/r/foobar2000/comments/mm70rb/i_made_an_opensource_alternative_to/h7uijix/
> Currently when we open the manual search window, we have these columns : Artist, Title, Album, Source . Can we also have LRC? this way we'll know if the lyrics are synced or not only by looking at the column

**Comment by ngs428** [comment]
This is one of my critical few too.  I think this is very much needed and a great time saver.  LSP3 has this and it is a very quick way to look at the search results and see which ones you need to use (in my case LRC files only).  Now, as you mentioned, you have to click on each one to see if they are timestamped or not.  Kind of a pain.  

Glad I found this open issue, because I think this would be a great addition.

**Comment by Rexadev** [comment]
Rename column to Un/Synced and Yes to Synced and No to UnSynced

**Comment by jacquesh** [comment]
> Rename column to Un/Synced and Yes to Synced and No to UnSynced

Please create a new issue (and provide at least a little bit of justification) so it can be properly tracked.

**Comment by Rexadev** [comment]
Add a checkbox to filter results to show only synced lyrics or Unsynced Lyrics it would solve other issues
