### ISSUE TITLE
Adding save option of the lyrics to the same folder and same name?

### ISSUE THREAD

**Issue by heeae** [jacquesh/foo_openlyrics#415]
Would it be possible to save the lyric to the same folder? 

With save to text file, it will save to a certain directory under foobar, and will not be available when moving to other foobar devices
With save to tag, it will write the music file, unlucky situation, the file may be corrupted  

Thanks

**Comment by jacquesh** [comment]
I think what you're looking for is the option at: `Preferences -> Tools -> OpenLyrics -> Search sources-> Local files -> Storage directory`

If you set that to `Same directory as the track` then it will save next to the audio file, instead of in fb2k's AppData folder.

Is that right? I'm going to assume so and close this for now, but if not then feel free to reply and we can re-open as needed.
