### ISSUE TITLE
Saving to the specified folder does not work

### ISSUE THREAD

**Issue by Mrakobes666** [jacquesh/foo_openlyrics#67]
Lyrics\%artist% - %title%  dont work

**Comment by Mrakobes666** [comment]
In theory, the presence of a slash should create a subfolder, and then a lyric file in it

[/url]  [url=http://i116.fastpic.org/big/2021/1030/c3/1dc79bca2d135f613a0db9fef7f221c3.png][img]http://i116.fastpic.org/thumb/2021/1030/c3/1dc79bca2d135f613a0db9fef7f221c3.jpeg[/img][/url]

**Comment by jacquesh** [comment]
That's because the path you've given is not a valid file path, you need an absolute path. In theory `$directory(%path%)` should do what you want but that doesn't work at the moment because I'm replacing path separators in the formatted path.

I'll take that out (you can achieve the same thing with `$replace`) and then you should be sorted. While I'm at  it I should probably include a link to the syntax help.

**Comment by Mrakobes666** [comment]
yes, I tried with variables, it didn't work. I will expect a solution
