### ISSUE TITLE
request: bandcamp.com

### ISSUE THREAD

**Issue by Mrakobes666** [jacquesh/foo_openlyrics#82]
A request for lyrics from a site that has a structure that parses well, this site is a trend for a huge number of musicians

https://deltasleep.bandcamp.com/album/spring-island?from=discover-top

![2021-12-07 17-48-37](https://user-images.githubusercontent.com/34971439/145051839-4cd654cf-859d-4e32-9c4b-af6dfeb1cc32.png)

**Comment by Rexadev** [comment]
Using Curl

```
// Include necessary libraries and headers
#include <string>
#include <curl/curl.h>

// Function to retrieve lyrics from Bandcamp
std::string getBandcampLyrics(const std::string& trackUrl) {
  std::string lyrics;
  
  // Make a request to the track URL
  CURL* curl = curl_easy_init();
  
  if (curl) {
    curl_easy_setopt(curl, CURLOPT_URL, trackUrl.c_str());
    curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
    
    // Specify any additional CURL options if required
    
    // Perform the HTTP request and retrieve the response
    CURLcode res = curl_easy_perform(curl);
    
    if (res == CURLE_OK) {
      // Process the response to extract the lyrics
      lyrics = extractLyricsFromResponse(curl);
    }
    
    // Clean up the CURL resources
    curl_easy_cleanup(curl);
  }
  
  return lyrics;
}

// Modify the existing fetchLyrics() function in the foo_openlyrics source file
void fetchLyrics(const std::string& trackUrl) {
  std::string lyrics;
  
  // Check if the track URL is from Bandcamp
  if (isBandcampTrack(trackUrl)) {
    lyrics = getBandcampLyrics(trackUrl);
  }
  
  // Handle the fetched lyrics as per the existing logic
  handleFetchedLyrics(lyrics);
}
```

**Comment by Rexadev** [comment]
@jacquesh When using this. Add option to only search on bandcamp.com when file has source metadata has word bandcamp in it.

**Comment by jacquesh** [comment]
Prompted by @Rexadev's request for filtering the search based on tag, I noticed that the tracks I have from bandcamp all include lyrics in their tags. So I checked the motivating example posted above and that has lyrics in tags too. So unless somebody wants to provide a solid justification to handle this as a remote source separately, I'm just going to say "music from bandcamp includes lyrics anyway, so there's no point in adding a separate source for it".

Sure, you may have gotten your music from a store other than bandcamp, but if its available elsewhere then there are probably lyrics elsewhere too?

**Comment by Rexadev** [comment]
https://github.com/ESLyric/scripts/blob/main/searcher/bandcamp.js

**Comment by jacquesh** [comment]
> This argument makes no sense when you are talking about Internet radio metadata, which of course doesn't send "lyrics in their tags" or involve getting music from a store. That is my "solid justification to handle this as a remote source separately."

I don't appreciate the emphasis and quoting here. It comes across to me as rude. I understand why you might be disappointed, but if there is a feature you particularly want, then just like any other permissively-licensed open-source project, you are welcome to take the time yourself to put together a decent-quality pull request that adds it. I don't ever use radio streams, so while I do try to keep them in mind when working on OpenLyrics, they're easy to miss. If that's a major use-case for you, then please try contributing the work needed to support them before berating me for choosing not to add a feature *right now* that is beneficial primarily to internet radio.

That said, since it was easy to do, I've added a source for Bandcamp to v1.11 (which is on its way out now).

@Rexadev If you would still like the option to only search bandcamp when the metadata contains the "Visit artist.bandcamp.com" message, then please open a dedicated ticket for it. I haven't done that.

**Comment by Rexadev** [comment]
Lyrics for this is at https://derbypdx.bandcamp.com/track/if-ever-theres-a-reason by openlyrics searches http://derby.bandcamp.com/track/if-ever-theres-a-reason

**Comment by Rexadev** [comment]
# Other Solutions

https://community.mp3tag.de/t/ws-bandcamp-search-by-album-or-track/17838

# API

https://bandcamp.com/developer

https://github.com/scriptkittie/bandcamp-api

https://github.com/michaelherger/Bandcamp-API

**Comment by jacquesh** [comment]
> Searching with pattern is not working for BandCamp.com is Search API possible

Please open a new ticket.
