### ISSUE TITLE
Saved file is not loaded

### ISSUE THREAD

**Issue by gabriels1963** [jacquesh/foo_openlyrics#91]
I have a file for a specific song save in the same folder and does not load.
I rescanned manually as the error suggested and saved the file again but it always come up with the same error.
![Clipboard01](https://user-images.githubusercontent.com/26761237/147149980-f20cd496-c2be-4932-8f9a-43d9e2bd80d6.jpg)

**Comment by Nojevah** [comment]
Maybe dev will need more information like the file or a video of the problem ?
File name ? The setting you chose for searching by file ?

**Comment by gabriels1963** [comment]
This is the filename:
1-01 Lights of Barcelona.dsf

This is the lyrics file that was created:
1-01 Lights of Barcelona.lrc

This is the content of the lyrics:
[99:00.00]Artist: Marc Vallee Trio
Album: Audiophile Analog Collection Vol. 2 
Title: Lights of Barcelona

The are all the setting for OpenLyrics:
![OpenLyrics](https://user-images.githubusercontent.com/26761237/147399967-66cdebba-8ef9-47fe-87e7-ef10679ce067.jpg)
![Display](https://user-images.githubusercontent.com/26761237/147399968-ffe71a74-b567-442f-b2af-046340ea9672.jpg)
![Editing](https://user-images.githubusercontent.com/26761237/147399971-2c4c7a5e-6a6f-41f0-bddc-3591628c14e5.jpg)
![Saving](https://user-images.githubusercontent.com/26761237/147399975-7ef9166f-e159-4437-9109-ce1a16e3c847.jpg)

**Comment by johbiii** [comment]
I have this same issue. I have a temporary fix (kind of).

The issue seems to be with songs being perma-added to a auto-skip list after x failed attempts to auto-search.

The list seems to be based off of tags. If you change the title of one of these songs, right-click on the panel > Search for lyrics. It will auto-load in the future if you are successful. However, the issue will return if you change the tag back to what it was before.

I am terrible with C++, I have no idea where it's storing info about 'always auto-skip' songs, but it is being stored. It is not instanced.

This also means that this bug should be install dependent, an issue with songs not getting cleared from an auto-skip list even after a successful search is saved locally or to tags.

**Comment by jacquesh** [comment]
@dinfinity Oh thanks for looking into it. Yes it only updates on save. I suppose it could be on the search (that should only affect you if you're *not* saving it though) and arguably that's the more "correct" place for it to be (since its the other side of the check that happens before search starts).

I can take a look at re-arranging this at some point.
